### ISSUE TITLE
Upgrade CRDs by Helm

### ISSUE THREAD

**Issue by m1n9o** [projectcapsule/capsule-proxy#520]
# Describe the feature

We can install Capsule and Capsule Proxy easily with Helm, however, Helm doesn't manage the upgrade of CRDs. See [here](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/).

# What would the new user story look like?

In order to let Helm to manage CRDs, it's nice to use two charts approach to do so.
Like,
```
resource "helm_release" "capsule-proxy-crds" {
  depends_on = [
    helm_release.capsule,
  ]

  name             = "capsule-proxy"
  repository       = "https://projectcapsule.github.io/charts"
  chart            = "capsule-proxy-chart"
  version          = "0.7.0"
  namespace        = "capsule-system"
  create_namespace = false
  atomic           = true
  cleanup_on_fail  = true
  values = [
    file("${path.module}/capsule-proxy-values.yaml"),
  ]
}

resource "helm_release" "capsule-proxy" {
  depends_on = [
    helm_release.capsule,
  ]

  name             = "capsule-proxy"
  repository       = "https://projectcapsule.github.io/charts"
  chart            = "capsule-proxy"
  version          = "0.7.0"
  namespace        = "capsule-system"
  create_namespace = false
  atomic           = true
  cleanup_on_fail  = true
}
```

# Expected behavior
A specific Helm chart for the CRDs is required.

**Comment by prometherion** [comment]
Poking here @oliverbaehler since took care of this, but it seems to me we're already overcoming Helm limitations about CRDs lifecycle.

https://github.com/projectcapsule/capsule-proxy/blob/f4608891984bb692dace74f67789cc1435e9b1af/charts/capsule-proxy/values.yaml#L5-L10

Furthermore, a detailed way to handle these updates has been documented with the v0.7.0 release: https://github.com/projectcapsule/capsule-proxy/tree/main/charts/capsule-proxy#07x

If you haven't tried this flow I'd say it would be great if you could try it by reporting any issue you encountered.

Otherwise, let's close this feature, mostly because I would like to keep the Issue section only for confirmed bug reports.

**Comment by m1n9o** [comment]
Thanks @prometherion , happy to close it. Seems `crds.install: true` is what I need for both installation and upgrade. ❤️
